_pimcore:
    resource: "@PimcoreCoreBundle/Resources/config/routing.yml"

homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /admin
        permanent: true

app:
    resource: "../src/Controller/"
    type: annotation

api_platform:
    resource: .
    type: api_platform
    prefix: /api

api_login_check:
    path: /api/login_check
    methods: ['POST']
