version: '3.7'

services:
    webserver:
        build: ./.docker/webserver
        hostname: ${HOSTNAME}
        ports:
            - "${NGINX_WEBSERVER_HTTP_PORT}:80"
            - "${NGINX_WEBSERVER_HTTPS_PORT}:443"
        volumes:
            - ./Source:/var/www/pimcore
        depends_on:
            - php

    php:
        build:
            context: ./.docker/php.local
            args:
              DISABLE_XDEBUG: ${DISABLE_XDEBUG:-1}
              USER_ID: "${USER_ID}"
        working_dir: /var/www/pimcore
        volumes:
            - ./Source:/var/www/pimcore:cached
        environment:
          TZ: "Europe/Berlin"
        depends_on:
            - db
            - redis
            - elasticsearch

    db:
        image: mariadb:10.5
        working_dir: /application
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
          - ${DATABASE_VOLUME:-db}:/var/lib/mysql
          # Use custom configuration parameters
          - ./.docker/db/conf.d:/etc/mysql/conf.d
        ports:
          - "${MYSQL_PORT}:3306"

    redis:
        build: ./.docker/redis
        ports:
            - "${REDIS_PORT}:6379"

    elasticsearch:
      build: ./.docker/elasticsearch
      ulimits:
        memlock:
          soft: -1
          hard: -1
        nofile: 65536
      volumes:
        - ${ELASTICSEARCH_VOLUME:-elasticsearch}:/usr/share/elasticsearch/data

volumes:
    db:
    elasticsearch:
      driver: local

