// @name Delete EndUser
DELETE {{api_scheme}}{{api_host}}/api/endusers/{{enduserId}}
Authorization: Bearer {{token}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 204, "Response status is not 204");
    });
%}