// @name Put EndUser status
PUT {{api_scheme}}{{api_host}}/api/endusers/{{enduserId}}/transition
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "transaction": "change_pending_start_date",
    "startDate": null,
    "endDate": null
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}