### View Company Custom Fields List 1
GET {{api_scheme}}{{api_host}}/api/companies/{{company_id}}/custom-fields
Authorization: Bearer {{token}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Add Company Custom Field
PATCH {{api_scheme}}{{api_host}}/api/companies/{{company_id}}/custom-fields
Authorization: Bearer {{token}}
Content-Type: application/merge-patch+json

{
    "name": {
        "en": "balance",
        "de": "balances"
    },
    "inputType": "integer",
    "key": "new-balance12"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### View Company Custom Fields List 2
GET {{api_scheme}}{{api_host}}/api/companies/{{company_id}}/custom-fields
Authorization: Bearer {{token}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

